version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv sync --group docs
    - uv run zensical build
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r site/* $READTHEDOCS_OUTPUT/html/
