use rstest::rstest;

use super::last_reply;

#[rstest]
#[case::zadd_counts_new(&["ZADD z 1 a 2 b", "ZADD z 3 a 4 c"], "1")]
#[case::zadd_ch_counts_changed(&["ZADD z 1 a", "ZADD z CH 3 a 4 c"], "2")]
#[case::zadd_nx_keeps_score(&["ZADD z 1 a", "ZADD z NX 5 a", "ZSCORE z a"], "\"1\"")]
#[case::zadd_xx_skips_new(&["ZADD z XX 1 a", "ZCARD z"], "0")]
#[case::zadd_gt(&["ZADD z 5 a", "ZADD z GT 3 a", "ZSCORE z a"], "\"5\"")]
#[case::zadd_lt(&["ZADD z 5 a", "ZADD z lt 3 a", "ZSCORE z a"], "\"3\"")]
#[case::zadd_nx_xx(&["ZADD z NX XX 1 a"], "-ERR XX and NX options at the same time are not compatible")]
#[case::zadd_gt_lt(&["ZADD z GT LT 1 a"], "-ERR GT, LT, and/or NX options at the same time are not compatible")]
#[case::zadd_nx_gt(&["ZADD z NX GT 1 a"], "-ERR GT, LT, and/or NX options at the same time are not compatible")]
#[case::zadd_odd(&["ZADD z 1 a 2"], "-ERR syntax error")]
#[case::zadd_no_members(&["ZADD z CH"], "-ERR wrong number of arguments for 'zadd' command")]
#[case::zadd_bad_score(&["ZADD z one a"], "-ERR value is not a valid float")]
#[case::zadd_nan(&["ZADD z nan a"], "-ERR value is not a valid float")]
#[case::zadd_infinite(&["ZADD z -inf a", "ZSCORE z a"], "\"-inf\"")]
#[case::zadd_fraction(&["ZADD z 1.5 a", "ZSCORE z a"], "\"1.5\"")]
#[case::zadd_wrong_type(&["SET z v", "ZADD z 1 a"], "-WRONGTYPE Operation against a key holding the wrong kind of value")]
#[case::zrem(&["ZADD z 1 a 2 b", "ZREM z a c"], "1")]
#[case::zcard_extra(&["ZCARD z y"], "-ERR syntax error")]
#[case::zcount(&["ZADD z 1 a 2 b 3 c", "ZCOUNT z 2 +inf"], "2")]
#[case::zcount_exclusive(&["ZADD z 1 a 2 b 3 c", "ZCOUNT z (1 (3"], "1")]
#[case::zcount_bad_bound(&["ZCOUNT z low 3"], "-ERR min or max is not a float")]
#[case::zcount_extra(&["ZCOUNT z 1 2 3"], "-ERR syntax error")]
#[case::zscore_missing(&["ZSCORE z a"], "nil")]
#[case::zscore_extra(&["ZSCORE z a b"], "-ERR syntax error")]
#[case::zrange(&["ZADD z 1 a 2 b 3 c", "ZRANGE z 0 -2"], "[\"a\", \"b\"]")]
#[case::zrange_withscores(&["ZADD z 1 a 2 b", "ZRANGE z 0 0 WITHSCORES"], "[\"a\", \"1\"]")]
#[case::zrange_unknown_option(&["ZRANGE z 0 1 REV"], "-ERR syntax error")]
#[case::zrange_bad_index(&["ZRANGE z a 1"], "-ERR value is not an integer or out of range")]
#[case::zrangebyscore(&["ZADD z 1 a 2 b 3 c", "ZRANGEBYSCORE z -inf (3"], "[\"a\", \"b\"]")]
#[case::zrangebyscore_withscores(&["ZADD z 1 a 2 b", "ZRANGEBYSCORE z 2 2 WITHSCORES"], "[\"b\", \"2\"]")]
#[case::zrangebyscore_limit(&["ZADD z 1 a 2 b 3 c", "ZRANGEBYSCORE z -inf +inf LIMIT 1 1"], "[\"b\"]")]
#[case::zrangebyscore_negative_count(&["ZADD z 1 a 2 b 3 c", "ZRANGEBYSCORE z -inf +inf LIMIT 1 -1"], "[\"b\", \"c\"]")]
#[case::zrangebyscore_negative_offset(&["ZADD z 1 a", "ZRANGEBYSCORE z -inf +inf LIMIT -1 5"], "[]")]
#[case::zrangebyscore_unknown_option(&["ZRANGEBYSCORE z 0 1 REV"], "-ERR syntax error")]
#[case::zremrangebyscore(&["ZADD z 1 a 2 b 3 c", "ZREMRANGEBYSCORE z (1 +inf", "ZRANGE z 0 -1"], "[\"a\"]")]
#[case::zremrangebyscore_extra(&["ZREMRANGEBYSCORE z 1 2 3"], "-ERR syntax error")]
#[tokio::test]
async fn sorted_sets(#[case] lines: &[&str], #[case] expected: &str) {
    assert_eq!(last_reply(lines).await, expected);
}
