name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          # Need full history for proper versioning with hatch-vcs
          fetch-depth: 0

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Install build dependencies
        run: uv pip install build hatchling hatch-vcs

      - name: Build package
        run: uv run python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          verify-metadata: true
